version: "3.8"

services:
  broadcast-grpc-server:
    container_name: broadcast-grpc-server
    volumes:
      - ./:/gabaithon-grpc-server
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    command: sh -c 'air'
